modLoader = "javafml" #mandatory
loaderVersion = "*" #mandatory
license = "${license_url}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "${issues_url}" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_display_name}" #mandatory
displayURL = "${homepage_url}" #optional (displayed in the mod UI)
logoFile = "logo.png" #optional
credits = "KiriCattus" #optional
authors = "KiriCattus" #optional
description = '''${mod_description}''' #mandatory (Supports multiline text)

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]] #optional
modId = "neoforge" #mandatory
mandatory = true
versionRange = "*" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
mc-publish = { ignore = true }

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "terrablender"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
mc-publish = { curseforge = "940057", modrinth = "kkmrDlKT" }

[mc-publish]
curseforge = "280003"
modrinth = "SrAIvfzS"
loaders = ["neoforge"]

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"

