modLoader = "javafml" #mandatory
loaderVersion = "[1,)" #mandatory
license = "${license_url}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "${mod_source}/issues" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "${display_url}" #optional (displayed in the mod UI)
logoFile = "logo.png" #optional
credits = "${credits}" #optional
authors = "${author}" #optional
description = '''${description}''' #mandatory (Supports multiline text)

[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type = "required"
versionRange = "${neoforge_version_range}" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "smartbrainlib"
required = true
versionRange = "[${smart_brain_lib_neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
required = true
versionRange = "[${geckolib_neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "resourcefulconfig"
required = true
versionRange = "[${resourceful_config_neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "terrablender"
type = "required"
versionRange = "[${terrablender_neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[mc-publish]
curseforge = "curseforge_id"
modrinth = "modrinth_id"
loaders = ["neoforge"]

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"

